name: "AniList"
guid: "1bd22884-44be-40f3-ad95-fc4a7834ba2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 11
targetAbi: "10.10.7.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Cleanup (#91) @Shadowghost

  ### New features and improvements ###
  - Added a setting to make only animation studio appear as metadata (with fixes) (#88) @sjorge
