name: "AniList"
guid: "1bd22884-44be-40f3-ad95-fc4a7834ba2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 14
targetAbi: "10.11.8.0"
framework: "net9.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Anime"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Allow filtering people by role (#110) @HansLehnert
  - Add anilist episode provider (#104) @ivanjx
  - Change image type for banner images from Backdrop to Banner (#109) @vodkapmp
