name: "AniList"
guid: "1bd22884-44be-40f3-ad95-fc4a7834ba2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 8
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Unstable (#61) @crobibero

  ### Bug Fixes ###
  - Fix genre settings not being applied to movies (#52) @HansLehnert
