name: "AniList"
guid: "1bd22884-44be-40f3-ad95-fc4a7834ba2c"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 10
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Support for retreiving Person metadata (#75) @HansLehnert

  ### Dependency updates ###
  - Update dotnet monorepo to 8.0.1 (#80) @renovate
